services:
  frontend:
    container_name: frontend
    build: ./requirements/frontend
    volumes:
      - ./requirements/frontend/app/:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    container_name: backend
    build: ./requirements/backend
    volumes:
      - ./requirements/backend/api/:/api
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"